apiVersion: v1
kind: Service
metadata:
  name: svc-app-backend
  namespace: ns-indri
  labels:
    project: indri
    app: backend
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: service
    tag: svc-app-backend
spec:
  type: ClusterIP
  selector:
    pod: pod-app-backend
  ports:
    - name: port-svc-app-be
      port: 8000
      targetPort: 8000