apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-postgres
  namespace: ns-indri
  labels:
    project: indri
    app: postgres
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-postgres-db
  template:
    metadata:
      name: pod-postgres-db
      namespace: ns-indri
      labels:
        pod: pod-postgres-db
    spec:
      containers:
      - name: pod-postgres-db
        image: postgres:17.10
        ports:
          - name: postgres-port
            containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: P@ssw0rd
          - name: POSTGRES_DB
            value: indri-db

