apiVersion: v1
kind: Secret
metadata:
  name: acr-pull-secret
  namespace: ns-indri
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ndacr20260924.azurecr.io": {
          "username": "aks-pull-token",
          "password": "745cmHKxgEIMXvvyjNrC51FgqokqPDsDSkcH46QHXe5A1PwwepNTJQQJ99CIACHYHv6Eqg7NAAABAZCR2Shq"
        }
      }
    }