apiVersion: v1
kind: Secret
metadata:
  name: acr-pull-secret
  namespace: ns-indri
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ndacr20260924.azurecr.io": {
          "username": "aks-pull-token",
          "password": "FHOTU4q5oLhKyo7nujmTRBsiQzKlG1D8IJHAABWOjLiKL7xCmGftJQQJ99CIACHYHv6Eqg7NAAABAZCRYVrS"
        }
      }
    }