apiVersion: v1
kind: Service
metadata:
  name: svc-postgres-db
  namespace: ns-indri
  labels:
    project: indri
    app: postgres-db
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: service   
spec:
  type: ClusterIP
  selector:
    pod: pod-postgres-db
  ports:
    - name: pgadmin-http
      port: 5432
      targetPort: 5432 