apiVersion: v1
kind: Service
metadata:
  name: svc-ingress-postgres
  namespace: ns-indri
  labels:
    project: indri
    app: postgres-db
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: service
    tag: svc-ingress-postgres   
spec:
  type: ClusterIP
  selector:
    pod: pod-postgres-db
  ports:
    - name: app-ingress-pt
      port: 8000
      targetPort: 5432 