apiVersion: v1
kind: Service
metadata:
  name: svc-pgadmin
  namespace: ns-indri
  labels:
    project: indri
    app: pgadmin
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: service    
spec:
  type: ClusterIP
  selector:
    pod: pod-pgadmin-db
  ports:
    - name: pgadmin-http
      port: 80
      targetPort: 80 