apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app-simulator
  namespace: ns-indri
  labels:
    project: indri
    app: simulator
    env: dev
    owner: nd
    team: platform
    costcenter: nd
    object: deployment
    tag: dep-app-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: app-simulator
  template:
    metadata:
      name: pod-app-simulator
      namespace: ns-indri
      labels:
        pod: app-simulator
    spec:
      imagePullSecrets:
      - name: acr-pull-secret
      containers:
        - name: app-ingest
          image: ndacr20260924.azurecr.io/app-simulator:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
